### ISSUE TITLE
Where to store admin pwd

### ISSUE THREAD

**Issue by nate-meir** [mpanighetti/add-securetoken-to-logged-in-user#8]
Perhaps I am reading this incorrectly - but I am confused as to which Jamf script Parameter value I would store the admin password under.

**Comment by WaveBirdDash** [comment]
The script prompts for password entry for the SecureToken admin [in an AppleScript alert.](https://github.com/mpanighetti/add-securetoken-to-logged-in-user/blob/main/Add%20SecureToken%20to%20Logged-In%20User.sh#L162-L169)

**Comment by nate-meir** [comment]
Okay - I understand that piece. I am just working on embedding it so it doesn't do the prompt - but I am getting a blank screen on the first prompt when i try that.

**Comment by WaveBirdDash** [comment]
For security reasons, I wouldn't generally advise storing account passwords in a script, but I've made a change in #9 so that the script defines all the account passwords up top. If you input your account's password there, it should pass the account's password validation and skip that prompt for password entry. Let me know if that works for you.
